usgs/time-series-services

- .bumpversion.cfg
Title
-----------
JIRA task: https://internal.cida.usgs.gov/jira/browse/IOW-168
Description
-----------
Added bumpversion file.
> Add bumpversion file

- README.md
Title
-----------
JIRA: https://internal.cida.usgs.gov/jira/browse/IOW-168
Description
-----------
Updated local configuration documentation.
> Updated readme with local configuration

- .bumpversion.cfg
- CHANGELOG.md
- DISCLAIMER.md
- LICENSE.md
- README.md
- code.json
- pom.xml
- src/main/java/gov/usgs/wma/waterdata/controller/VersionController.java
Title
-----------
JIRA: https://internal.cida.usgs.gov/jira/browse/IOW-168
Description
-----------
Implementing some initial review feedback
> Making some changes after initial code review

- pipeline.yml
- pom.xml
- src/main/java/gov/usgs/wma/waterdata/swagger/SwaggerConfig.java
- src/main/resources/application.yml
Title
-----------
JIRA: https://internal.cida.usgs.gov/jira/browse/IOW-168
Description
-----------
Updated swagger config.
> Updated swagger config and removed extra dependency.

- CHANGELOG.md
Title
-----------
Description
-----------
> changelog update for release

- Jenkins.build
- Jenkins.deploy
Title
-----------
Description
-----------
> [IOW-123] - Use master for pipeline deploy logic

- CHANGELOG.md
- Jenkins.build
- Jenkins.deploy
Title
-----------
Description
-----------
> IOW-289 changelog update for release

- src/main/java/gov/usgs/wma/waterdata/collections/CollectionsController.java
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionsDao.java
- src/main/java/gov/usgs/wma/waterdata/collections/ObservationsController.java
- src/main/java/gov/usgs/wma/waterdata/collections/observations/ObservationTypeJSON.java
- src/main/java/gov/usgs/wma/waterdata/collections/observations/ObservationsJSON.java
- src/main/resources/mybatis/observations.xml
- src/test/java/gov/usgs/wma/waterdata/collections/BaseCollectionsIT.java
- src/test/java/gov/usgs/wma/waterdata/collections/CollectionsControllerIT.java
- src/test/java/gov/usgs/wma/waterdata/collections/FeaturesParamsIT.java
- src/test/java/gov/usgs/wma/waterdata/collections/ObservationsIT.java
- src/test/resources/testResult/observations.json
Added endpoint: collections/{collectionId}/items/{monitoring-location-identifier}/observations
New test: ObservationsIT
Refactored tests to extend from a base class BaseCollectionsIT, which contains the common helper
methods called by each test.
New method in CollectionsDao
New swagger schema classes: ObservationTypeJSON & ObservationsJSON
Title
-----------
Description
-----------
> IOW-359 (OGCAPI API extension to access statistical time series)

- .gitignore
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionsController.java
- src/main/java/gov/usgs/wma/waterdata/collections/ObservationsController.java
- src/main/java/gov/usgs/wma/waterdata/collections/ObservationsStatTimeSeriesController.java
- src/test/java/gov/usgs/wma/waterdata/collections/CollectionsControllerIT.java
- src/test/java/gov/usgs/wma/waterdata/collections/CollectionsObservationsIT.java
- src/test/java/gov/usgs/wma/waterdata/collections/ObservationsStatTimeSeriesControllerIT.java
Title
-----------
see PR title
Description
-----------
see PR title
> IOW-361 refactor the time series from root collecitons to observations API

- codecov.yml
- src/main/java/gov/usgs/wma/waterdata/GlobalDefaultExceptionHandler.java
- src/main/java/gov/usgs/wma/waterdata/OgcException.java
- src/main/java/gov/usgs/wma/waterdata/collections/BaseController.java
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionParams.java
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionsController.java
- src/main/java/gov/usgs/wma/waterdata/collections/ObservationsStatTimeSeriesController.java
- src/main/java/gov/usgs/wma/waterdata/parameter/BoundingBox.java
- src/main/java/gov/usgs/wma/waterdata/validation/BBox.java
- src/main/java/gov/usgs/wma/waterdata/validation/BBoxValidator.java
- src/test/java/gov/usgs/wma/waterdata/GlobalDefaultExceptionHandlerTest.java
- src/test/java/gov/usgs/wma/waterdata/collections/BaseCollectionsIT.java
- src/test/java/gov/usgs/wma/waterdata/collections/BoundingBoxTest.java
- src/test/java/gov/usgs/wma/waterdata/collections/CollectionParamsTest.java
- src/test/java/gov/usgs/wma/waterdata/collections/CollectionsControllerIT.java
- src/test/java/gov/usgs/wma/waterdata/collections/FeaturesParamsIT.java
- src/test/java/gov/usgs/wma/waterdata/collections/ObservationsStatTimeSeriesControllerIT.java
- src/test/java/gov/usgs/wma/waterdata/collections/ParamValidationIT.java
- src/test/resources/testResult/featureCollection/ANC/featureCollection_bbox_one.json
- src/test/resources/testResult/featureCollection/monitoring-locations/featureCollection_bbox_one.json
initial commit.
Title
-----------
Description
-----------
> IOW-366 (Support 400, 404, and 500 by OGC guidance)

- PULL_REQUEST_TEMPLATE.md
Title
-----------
Description
-----------
> Add swagger check to pull request template

- src/main/java/gov/usgs/wma/waterdata/springinit/SpringConfig.java
- src/main/java/gov/usgs/wma/waterdata/timeseries/TimeSeriesController.java
- src/test/resources/testResult/featureCollection/ANC/featureCollection_bbox_one.json
- src/test/resources/testResult/featureCollection/monitoring-locations/featureCollection_bbox_one.json
Title
-----------
Description
-----------
> Add cors mapping and fix broken unit test

- CHANGELOG.md
Title
-----------
Description
-----------
> changelog update for 0.5.0 release.

- CHANGELOG.md
- src/main/resources/mybatis/collections.xml
- src/test/resources/testData/monitoringLocation/network.csv
- [x ] Make sure all tests run
- [x ] Update the changelog appropriately
- [x ] Make sure the Swagger docs are accurate
Title
-----------
IOW-408 Modify collections endpoint to use new properties column 
Collections endpoint now uses NETWORK.properties column instead of contact_info column.  Added coalesce() function to handle null values.  Modified test source file to include properties field.
-----------
> IOW-408 Modify collections endpoint to populate properties 

- CHANGELOG.md
- [x ] Make sure all tests run
- [x ] Update the changelog appropriately
- [x ] Make sure the Swagger docs are accurate
Title
----------
Update changelog to reflect Release version 0.5.0 
-----------
- [x ] If appropriate, put the link to the PR in the JIRA ticket
- [x ] Assign someone to review unless the change is trivial
> Update changelog to reflect Release version 0.5.0 

- CHANGELOG.md
- src/main/resources/mybatis/observations.xml
- src/test/resources/testResult/observations.json
Updated mybatis/observations.xml to add discrete-data
entry to the observationTypes array returned in the json.
Add entry for discrete-data in testResult/observations.json
Updated CHANGELOG.md
Title
-----------
Description
-----------
> IOW-479 (Add a discrete-values endpoint)

- pom.xml
- src/main/java/gov/usgs/wma/waterdata/BaseController.java
- src/main/java/gov/usgs/wma/waterdata/RedirectController.java
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionsController.java
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionsDao.java
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionsStatTimeSeriesController.java
- src/main/java/gov/usgs/wma/waterdata/collections/ObservationsController.java
- src/main/java/gov/usgs/wma/waterdata/collections/ObservationsStatTimeSeriesController.java
- src/main/java/gov/usgs/wma/waterdata/features/FeaturesController.java
- src/main/java/gov/usgs/wma/waterdata/features/FeaturesDao.java
- src/main/java/gov/usgs/wma/waterdata/openapi/ConfigOpenApi.java
- src/main/java/gov/usgs/wma/waterdata/openapi/responses/Http200Response.java
- src/main/java/gov/usgs/wma/waterdata/openapi/responses/Http400Response.java
- src/main/java/gov/usgs/wma/waterdata/openapi/responses/Http404Response.java
- src/main/java/gov/usgs/wma/waterdata/openapi/responses/Http500Response.java
- src/main/resources/application.yml
- src/main/resources/mybatis/features.xml
- src/test/java/gov/usgs/wma/waterdata/RedirectControllerTest.java
- src/test/java/gov/usgs/wma/waterdata/collections/CollectionsControllerIT.java
- src/test/java/gov/usgs/wma/waterdata/collections/CollectionsDaoIT.java
- src/test/java/gov/usgs/wma/waterdata/features/BoundingBoxTest.java
- src/test/java/gov/usgs/wma/waterdata/features/FeaturesControllerIT.java
- src/test/java/gov/usgs/wma/waterdata/features/FeaturesDaoIT.java
- src/test/java/gov/usgs/wma/waterdata/openapi/SpringDocIT.java
- src/test/resources/application.yml
Title
-----------
Description
-----------
> Wip iow 356

- Jenkins.deploy
Title
-----------
Description
-----------
> Updated Jenkins deploy to use team:iow agent.

- Jenkins.build
- Jenkins.deploy
Title
-----------
Description
-----------
> Updated Jenkins iow-ecs-pipeline library to version 2.2.0

- Jenkins.build
Title
-----------
Description
-----------
> Updated agent to team:iow in Jenkins.build

- CHANGELOG.md
Title
-----------
Description
-----------
> CHANGELOG.md update for 0.7.0 release.

- CHANGELOG.md
- src/main/java/gov/usgs/wma/waterdata/openapi/schema/collections/FeatureGeoJSON.java
Title
-----------
Add default links block to swagger template for /collections/{collectionId}/items/{featureId}
Description
-----------
Someone already added links to /collections/{collectionId}/items between the time this ticket was written and I picked it up.
> add links to swagger example for Feature output IOW-536

- CHANGELOG.md
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionParams.java
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionsController.java
- src/main/java/gov/usgs/wma/waterdata/openapi/schema/collections/FeatureGeoJSON.java
- src/main/resources/mybatis/features.xml
- src/test/java/gov/usgs/wma/waterdata/collections/CollectionParamsTest.java
- src/test/java/gov/usgs/wma/waterdata/collections/FeaturesFilterIT.java
Title
-----------
Make agencyCode, monitoringLocationNumber, and nationalAquiferCode into lists.
The JIRA ticket also says to put nationalAquiferCode in the json output, but looks like that is already done.
Description
-----------
> Tweaks to items endpoint (IOW-596)

- CHANGELOG.md
Title
-----------
Description
-----------
> CHANGELOG.md  update to prepare for 0.8.0 release.

- Jenkins.build
- Jenkins.deploy
Title
-----------
Description
-----------
Point to the master branch of the ecs pipeline to enable move to fargate.
> IOW-709 move to fargate

- CHANGELOG.md
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionsController.java
- [ x ] Make sure all tests run
- [ x ] Update the changelog appropriately
- [ x ] Make sure the Swagger docs are accurate
Title
-----------
fixed swagger description for collection
Description
-----------
In the swagger docs for the observations endpoint, the description for the "/collections" endpoints and the "/collections/
{collectionId}
are described as "Return GeoJSON". Neither of these endpoints return GeoJSON but are defined by the OGC Features specification. These descriptions need to be corrected so as not to mislead the user of this documentation
Instead of "GeoJSON" use "OGCAPI JSON."
> fixed swagger description for collection

- Jenkins.build
- Jenkins.deploy
Title
-----------
Description
-----------
> use the new ecs deploy pipeline tag

- pipeline.yml
Title
-----------
https://internal.cida.usgs.gov/jira/browse/IOW-786
Description
-----------
> tag update - consolidate uppercase convention for wma:organization tag

- pom.xml
- src/test/java/gov/usgs/wma/waterdata/GlobalDefaultExceptionHandlerTest.java
Updated GlobalDefaultExceptionHandlerTest to handle the new
exception wording from Spring.
Title
-----------
Description
-----------
> Maintenance -- Updated spring-boot-starter-parent to version 2.4.5

- CHANGELOG.md
- src/main/java/gov/usgs/wma/waterdata/collections/BaseController.java
- src/main/java/gov/usgs/wma/waterdata/timeseries/TimeSeriesController.java
- src/main/java/gov/usgs/wma/waterdata/timeseries/TimeSeriesDao.java
- src/main/resources/mybatis/groundwaterDailyValueWaterML.xml
- src/test/java/gov/usgs/wma/waterdata/springinit/BaseIT.java
- src/test/java/gov/usgs/wma/waterdata/timeseries/TimeSeriesControllerIT.java
- src/test/java/gov/usgs/wma/waterdata/timeseries/TimeSeriesControllerXmlIT.java
- src/test/resources/testResult/xml/e6a4cc2de5bf437e83efe0107cf026ac.xml
- src/test/resources/testResult/xml/e6a4cc2de5bf437e83efe0107cf026ac_1095.xml
Specially /collections/{collectionId}/items/{featureId}/observations/statistical-time-series/{timeSeriesId}
will return WaterML if the content parameter (f) specifies xml format.
Title
-----------
Description
-----------
> IOW-619 -- Addition of WaterML as a content option.

- CHANGELOG.md
- README.md
- src/main/java/gov/usgs/wma/waterdata/BaseController.java
- src/main/java/gov/usgs/wma/waterdata/GlobalDefaultExceptionHandler.java
- src/main/java/gov/usgs/wma/waterdata/collections/BaseController.java
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionParams.java
- src/main/java/gov/usgs/wma/waterdata/collections/CollectionsController.java
- src/main/java/gov/usgs/wma/waterdata/collections/ObservationsController.java
- src/main/java/gov/usgs/wma/waterdata/data/DataController.java
- src/main/java/gov/usgs/wma/waterdata/parameter/ContentType.java
- src/main/java/gov/usgs/wma/waterdata/parameter/DataType.java
- src/main/java/gov/usgs/wma/waterdata/parameter/Domain.java
- src/main/java/gov/usgs/wma/waterdata/timeseries/TimeSeriesController.java
- src/main/java/gov/usgs/wma/waterdata/timeseries/TimeSeriesDao.java
- src/main/resources/mybatis/groundwaterDailyValueWaterML.xml
- src/test/java/gov/usgs/wma/waterdata/collections/CollectionParamsTest.java
- src/test/java/gov/usgs/wma/waterdata/data/DataControllerIT.java
- src/test/java/gov/usgs/wma/waterdata/springinit/BaseIT.java
- src/test/java/gov/usgs/wma/waterdata/timeseries/TimeSeriesControllerXmlIT.java
- src/test/resources/testResult/xml/dataEndPoint/1095/USGS-07227448.xml
- src/test/resources/testResult/xml/dataEndPoint/1095/USGS-07227448_best_false.xml
- src/test/resources/testResult/xml/dataEndPoint/1095/USGS-07227448_best_true.xml
- src/test/resources/testResult/xml/dataEndPoint/USGS-07227448.xml
- src/test/resources/testResult/xml/dataEndPoint/USGS-07227448_best_false.xml
- src/test/resources/testResult/xml/dataEndPoint/USGS-07227448_best_true.xml
Returns multiple time series in one WaterML
Refactored logic to determine content type is BaseController
New enums for /data parameters
New test: DataControllerIT
Title
-----------
Description
-----------
> NGWMN-2099 -- New endpoint /data

- src/main/java/gov/usgs/wma/waterdata/data/DataController.java
- src/main/java/gov/usgs/wma/waterdata/timeseries/TimeSeriesDao.java
- src/main/resources/mybatis/groundwaterDailyValue.xml
- src/test/java/gov/usgs/wma/waterdata/data/DataControllerJsonIT.java
- src/test/java/gov/usgs/wma/waterdata/timeseries/TimeSeriesDao1095IT.java
- src/test/java/gov/usgs/wma/waterdata/timeseries/TimeSeriesDaoIT.java
Updated groundwaterDailyValue.xml and dao to accept bestTS
parameter
New test: DataControllerJsonIT
Made monitoringLocationID query parameter required.
Title
-----------
Description
-----------
> NGWMN-2099 -- Added json output to /data end point.

- src/main/java/gov/usgs/wma/waterdata/data/DataController.java
- src/main/java/gov/usgs/wma/waterdata/openapi/schema/observations/StatisticalTimeSeriesItem.java
- src/test/java/gov/usgs/wma/waterdata/data/DataControllerJsonIT.java
Title
-----------
Description
-----------
> IOW-965 -- Added best field to openapi StatisticalTimeSeriesItem

- pom.xml
- src/main/java/gov/usgs/wma/waterdata/data/DataController.java
- src/main/java/gov/usgs/wma/waterdata/domain/WaterMLPoint.java
- src/main/java/gov/usgs/wma/waterdata/format/InheritNamespaceAnnotationIntrospector.java
- src/main/java/gov/usgs/wma/waterdata/format/WaterMLPointToXmlResultHandler.java
- src/main/resources/mybatis/discreteGWWaterMLPoint.xml
- src/test/java/gov/usgs/wma/waterdata/collections/FeaturesFilterHucLenIT.java
- src/test/java/gov/usgs/wma/waterdata/collections/FeaturesFilterIT.java
- src/test/java/gov/usgs/wma/waterdata/data/DataControllerDiscreteXmlIT.java
- src/test/java/gov/usgs/wma/waterdata/discrete/DiscreteDaoIT.java
- src/test/java/gov/usgs/wma/waterdata/format/WaterMLPointToXmlResultHandlerTest.java
*) Dependency updates in pom.xml, removed specifying version
for modules managed by Spring.
*) Some code clean of warnings (unused imports, etc).
*) Added http 404 if no results streamed.
*) Fixed test DataControllerDiscreteXmlIT.notFoundTest()
*) Removed unused properties/fields from WaterMLPoint
*) No longer flush response output after every point
Title
-----------
Description
-----------
> IOW-965 -- Refactor and Clean up.

- pom.xml
- src/main/resources/mybatis/groundwaterDailyValueWaterML.xml
- src/main/resources/mybatis/timeSeries.xml
- src/test/resources/testData/bestTimeSeries/csv/best_time_series.csv
Added 'and rank_type = 'GW_DAILY' and time_series_unique_id is not null'
to sql.
Added non time series ranking to test data.
Title
-----------
Description
-----------
> IOW-981 -- Update to handle rank_type column in best_time_series table.

- src/main/resources/mybatis/discreteGWWaterMLPoint.xml
- src/test/java/gov/usgs/wma/waterdata/data/DataControllerDiscreteXmlIT.java
- src/test/java/gov/usgs/wma/waterdata/format/WaterMLPointToXmlResultHandlerTest.java
- src/test/resources/testResult/xml/discrete/USGS-175848066350900.xml
- src/test/resources/testResult/xml/discrete/resultHandlerTest.xml
Added <om:phenomenonTime> and <om:resultTime> elements.
Updated DataControllerDiscreteXmlIT to perform schema validation.
Title
-----------
Description
-----------
> IOW-980 -- made discrete WaterML xml schema compliant.
